server:
  port: ${SERVER_PORT:8080}

spring:
  application:
    name: api-gateway
  security:
    oauth2:
      resourceserver:
        jwt:
          issuer-uri: ${KEYCLOAK_ISSUER_URI:http://localhost:8180/realms/innovatech}
  cloud:
    gateway:
      server:
        webmvc:
          routes:
            - id: bff
              uri: lb://bff-gateway
              predicates:
                - Path=/api/**
              filters:
                - StripPrefix=0
            - id: docs-bff
              uri: lb://bff-gateway
              predicates:
                - Path=/docs/bff/**
              filters:
                - RewritePath=/docs/bff/(?<segment>.*), /${segment}
            - id: docs-ms-usuarios
              uri: lb://ms-usuarios
              predicates:
                - Path=/docs/ms-usuarios/**
              filters:
                - RewritePath=/docs/ms-usuarios/(?<segment>.*), /${segment}
            - id: docs-ms-proyectos
              uri: lb://ms-proyectos
              predicates:
                - Path=/docs/ms-proyectos/**
              filters:
                - RewritePath=/docs/ms-proyectos/(?<segment>.*), /${segment}
    discovery:
      enabled: true

eureka:
  client:
    service-url:
      defaultZone: ${EUREKA_URL:http://localhost:8761/eureka/}
    fetch-registry: true
    register-with-eureka: true
  instance:
    prefer-ip-address: true

management:
  endpoints:
    web:
      exposure:
        include: health,info
